1) Moved n_body.hpp into the include directory 2) Added install targets to the CMAKELISTS.txt file 3) Added a panic function to the demo file 4) Added lines to the demo file to take the initial_state.txt file    and pass it into the n_body program 5) Used the panic function for the case inwhich the program fails

diff --git a/demo b/demo
--- a/demo
+++ b/demo
@@ -1,3 +1,17 @@
 #! /usr/bin/bash
 
-./n_body < initial_state.txt
+# Print an error message and exit.
+panic()
+{
+	echo "ERROR: $@"
+	exit 1
+}
+
+# Get install-bin directory
+cmd_dir=$(dirname "$0") || panic "cannot determine command directory"
+
+n_body_program="$cmd_dir/n_body"
+init_state="$cmd_dir/initial_state.txt"
+echo "Running n_body program demo"
+$n_body_program < $init_state || panic "n_body program demo failed"
+
